---
dist: xenial
sudo: required
language: generic
addons:
  apt:
    packages:
      - python3
      - python3-pip
git:
  submodules: false
before_install:
  - sudo pip3 install vim-vint==0.3.21
script: |
  find . -type f -name '*.vim' -exec vint -s '{}' +
