name: Checks

on: [push, pull_request]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        pip3 install --user vim-vint==0.3.21

    - name: Run vint
      run: |
        find . -type f -name '*.vim' -exec vint -s '{}' +
